### ISSUE TITLE
Filters should be named according to their usage

### ISSUE THREAD

**Issue by petersalemink95** [alliander-opensource/power-grid-model-io#11]
Example:
Now the Vision converter uses a filter `get_winding_from` 

This function name should either be changed to  `vision_get_winding_from`  or the function should be in a separate folder/file e.g. `vision_filters.py` 

The structure/naming of all filters should be checked and improved

**Comment by bramstoeller** [comment]
This has been fixed in PR #13

**Comment by bramstoeller** [comment]
This issue has been fixed in #13
