### ISSUE TITLE
bug in tabular converter with cross reference to node

### ISSUE THREAD

**Issue by TonyXiang8787** [alliander-opensource/power-grid-model-io#25]
In here
https://github.com/alliander-opensource/power-grid-model-io/blob/8612f197037a3ab10a9ce31e52f9c2eb8869e713/src/power_grid_model_io/converters/tabular_converter.py#L196

```python
elif attr.endswith("node"):
            # Atributes that end with "node" are refences to nodes. Currently this is the only type of reference
            # that is supported.
            attr_data = self._handle_node_ref_column(data=data, table=table, col_def=col_def)
```
It determines if a cross reference is to a node by judging if the attribute ends with “node”. This is not correct. In three winding transformers, the cross reference attribute is called `node_1`, `node_2`, and `node_3`.

**Comment by bramstoeller** [comment]
Of course there's an easy fix, by adjusting the string match with a regex or something. But this issue relates to https://github.com/alliander-opensource/power-grid-model-io/issues/9, where we could define `node_1` etc as:
```yaml
node_1:
  auto_id:
    component: node:
    key:
      node_id: hv_bus
```

**Comment by bramstoeller** [comment]
After some discussion with @petersalemink95, we have decided that will keep the auto-magical node reference mechanism, for simplicity and convenience. So for now we'll abandon my previous suggestion and use this notation instead:
```yaml
node_1: hv_bus
```
I've fixed the issue using a regular expression.
