### ISSUE TITLE
SimBench data loader

### ISSUE THREAD

**Issue by bramstoeller** [alliander-opensource/power-grid-model-io#28]
Create a SimBenchConverter that downloads and extracts a sim bench dataset (using a download util), reads the data (using a CsvDirStore) and converts it to PGM data (using a SimBenhConverter + mapping file).

**Comment by nitbharambe** [comment]
Documentation: https://simbench.de/wp-content/uploads/2020/01/simbench_documentation_en_1.0.0.pdf
Simbench examples are dervied from a single large grid. The examples are subdivided based on applications like rural and urban. For start we can use the 1-MV-rural--0-sw grid. Or any grid with the `MV` and `LV` codes

Note:

- Unsupported Content: EHV grids (PowerPlants.csv). Note that the `calc_type` is `pvm` which means pv type. (Pg. 94 of pdf)
- No data for asymmetric calculations
