### ISSUE TITLE
Add a discription to this repo in the about section

### ISSUE THREAD

**Issue by Jonasvdbo** [alliander-opensource/power-grid-model-io#38]
A suggestion for enhancement is to add a description to this repo.

![image](https://user-images.githubusercontent.com/3628277/197198351-f761c8f0-3544-4e16-91a8-0d859992fa93.png)

For example:

power-grid-model-io can be used for various conversions to the power-grid-model.

**Comment by nitbharambe** [comment]
Added one. Thanks for the suggestion.
