### ISSUE TITLE
int64 bug

### ISSUE THREAD

**Issue by bramstoeller** [alliander-opensource/power-grid-model-io#83]
It is possible that the original (vision) id's are represented by `numpy.int64` values. As a results the `int64`s end up in the extra info dictionary. Unfortunately `int64` is not json serializable by default, so storing the data using the `PgmJsonConverter` is no longer possible and will result in a `TypeError: Object of type int64 is not JSON serializable`.

This bug should be thought of more generally... How do we handle non json serializable IDs / info?

**Comment by TonyXiang8787** [comment]
@bramstoeller we can just convert `numpy.int64` to just normal `int` in the dictionary which will be serialized in json.

**Comment by bramstoeller** [comment]
Well, I would like to keep the original type, as the type can be anything and it would be perfectly valid to have special types in the `extra_info` to use in your python code. So I'd like to use a custom serializer for numpy types (and maybe other types in the future) like:

```python
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NpEncoder, self).default(obj)
```
(borrowed from https://stackoverflow.com/questions/50916422/python-typeerror-object-of-type-int64-is-not-json-serializable)
