### ISSUE TITLE
Feature request: dutch mapping

### ISSUE THREAD

**Issue by jaapschoutenalliander** [alliander-opensource/power-grid-model-io#90]
I would like to be able to convert dutch Vision Excels, since our users are all using Vision in dutch. I am already working on a mapping in https://github.com/Alliander/holonet-vision-job/blob/develop/holonet_vision_job/resources/vision_nl.yaml, maybe when this is final we can add it to the power-grid-model-io repo?

**Comment by TonyXiang8787** [comment]
@jaapschoutenalliander nice to see the development. When you have tested and finalized it, feel free to make a PR to add to this repo.

You can use this Vision test file to test your mapping.
https://github.com/alliander-opensource/power-grid-model-io/blob/main/tests/data/vision/vision_validation.vnf
